import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "fr" | "ar";

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.journey": "Journey",
    "nav.education": "Education",
    "nav.experience": "Experience",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.ieee": "IEEE",
    "nav.awards": "Awards",
    "nav.testimonials": "Testimonials",
    "nav.uses": "Uses",
    "nav.contact": "Contact",
    "hero.greeting": "Hey there, I'm",
    "hero.currently": "Currently building:",
    "hero.at": "@ ADVISING LTD",
    "hero.download": "Download CV",
    "hero.view": "View Projects",
    "hero.available": "Available for Opportunities",
    "hero.badge": "Seeking Work-Study Program · Open to Opportunities",
    "about.title": "Who I Am",
    "about.subtitle": "Computer Science student with a passion for AI and full-stack development",
    "about.github": "GitHub Activity",
    "about.open": "Open to Opportunities",
    "about.open.sub": "International internships · Graduate programs · Global tech roles",
    "skills.title": "Technical Expertise",
    "skills.subtitle": "A comprehensive tech stack spanning AI, frontend, backend, and cloud",
    "experience.title": "Work Experience",
    "experience.subtitle": "Professional internships and engineering roles",
    "projects.title": "Projects",
    "projects.subtitle": "A selection of things I've built",
    "education.title": "Academic Journey",
    "education.subtitle": "The academic path that shaped my technical foundation",
    "contact.title": "Get In Touch",
    "contact.subtitle": "Let's collaborate and build something amazing together",
    "testimonials.title": "Kind Words",
    "testimonials.subtitle": "What colleagues and supervisors say about working with me",
    "journey.title": "My Story",
    "journey.subtitle": "The story behind the code — milestones that shaped who I am",
    "ieee.title": "IEEE Leadership",
    "ieee.subtitle": "Driving innovation and community across local, regional, and global IEEE initiatives",
    "awards.title": "Awards & Honors",
    "awards.subtitle": "Awards, certifications, and achievements",
    "uses.title": "My Setup",
    "uses.subtitle": "The tools, software, and hardware I use every day",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.journey": "Parcours",
    "nav.education": "Éducation",
    "nav.experience": "Expérience",
    "nav.projects": "Projets",
    "nav.skills": "Compétences",
    "nav.ieee": "IEEE",
    "nav.awards": "Prix",
    "nav.testimonials": "Avis",
    "nav.uses": "Outils",
    "nav.contact": "Contact",
    "hero.greeting": "Bonjour, je suis",
    "hero.currently": "En cours de développement :",
    "hero.at": "@ ADVISING LTD",
    "hero.download": "Télécharger CV",
    "hero.view": "Voir les projets",
    "hero.available": "Disponible pour des opportunités",
    "hero.badge": "Programme alternance · Ouvert aux opportunités",
    "about.title": "Qui suis-je",
    "about.subtitle": "Étudiant en informatique passionné par l'IA et le développement full-stack",
    "about.github": "Activité GitHub",
    "about.open": "Ouvert aux opportunités",
    "about.open.sub": "Stages internationaux · Programmes de master · Postes tech mondiaux",
    "skills.title": "Expertise Technique",
    "skills.subtitle": "Une stack complète couvrant IA, frontend, backend et cloud",
    "experience.title": "Expérience Pro",
    "experience.subtitle": "Stages professionnels et rôles d'ingénierie",
    "projects.title": "Projets",
    "projects.subtitle": "Une sélection de ce que j'ai construit",
    "education.title": "Parcours Académique",
    "education.subtitle": "Le parcours académique qui a forgé mes bases techniques",
    "contact.title": "Me Contacter",
    "contact.subtitle": "Collaborons et construisons quelque chose d'incroyable",
    "testimonials.title": "Témoignages",
    "testimonials.subtitle": "Ce que disent collègues et superviseurs",
    "journey.title": "Mon Parcours",
    "journey.subtitle": "L'histoire derrière le code — les étapes qui m'ont façonné",
    "ieee.title": "Leadership IEEE",
    "ieee.subtitle": "Promouvoir l'innovation et la communauté à travers les initiatives IEEE locales, régionales et mondiales",
    "awards.title": "Prix & Distinctions",
    "awards.subtitle": "Récompenses, certifications et réalisations",
    "uses.title": "Mon Environnement",
    "uses.subtitle": "Les outils, logiciels et matériels que j'utilise chaque jour",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.about": "عني",
    "nav.journey": "مسيرتي",
    "nav.education": "التعليم",
    "nav.experience": "الخبرة",
    "nav.projects": "المشاريع",
    "nav.skills": "المهارات",
    "nav.ieee": "IEEE",
    "nav.awards": "الجوائز",
    "nav.testimonials": "الآراء",
    "nav.uses": "الأدوات",
    "nav.contact": "التواصل",
    "hero.greeting": "مرحباً، أنا",
    "hero.currently": "أعمل حالياً على:",
    "hero.at": "@ ADVISING LTD",
    "hero.download": "تحميل السيرة الذاتية",
    "hero.view": "عرض المشاريع",
    "hero.available": "متاح للفرص",
    "hero.badge": "برنامج التعاون مع المؤسسات · مفتوح للفرص",
    "about.title": "من أنا",
    "about.subtitle": "طالب علوم الحاسوب شغوف بالذكاء الاصطناعي والتطوير الشامل",
    "about.github": "نشاط GitHub",
    "about.open": "متاح للفرص",
    "about.open.sub": "تدريبات دولية · برامج الدراسات العليا · وظائف تقنية عالمية",
    "skills.title": "الخبرة التقنية",
    "skills.subtitle": "مجموعة تقنيات شاملة تغطي الذكاء الاصطناعي والواجهات والخلفيات والسحابة",
    "experience.title": "الخبرة المهنية",
    "experience.subtitle": "تدريبات مهنية وأدوار هندسية",
    "projects.title": "المشاريع",
    "projects.subtitle": "مجموعة مختارة مما بنيته",
    "education.title": "المسيرة الأكاديمية",
    "education.subtitle": "المسار الأكاديمي الذي شكّل أسسي التقنية",
    "contact.title": "تواصل معي",
    "contact.subtitle": "لنتعاون ونبني شيئاً رائعاً معاً",
    "testimonials.title": "كلمات طيبة",
    "testimonials.subtitle": "ما يقوله الزملاء والمشرفون عن العمل معي",
    "journey.title": "قصتي",
    "journey.subtitle": "القصة خلف الكود — المحطات التي شكّلت مسيرتي",
    "ieee.title": "قيادة IEEE",
    "ieee.subtitle": "دفع الابتكار والمجتمع عبر مبادرات IEEE المحلية والإقليمية والعالمية",
    "awards.title": "الجوائز والتكريمات",
    "awards.subtitle": "الجوائز والشهادات والإنجازات",
    "uses.title": "بيئة عملي",
    "uses.subtitle": "الأدوات والبرامج والأجهزة التي أستخدمها يومياً",
  },
};

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string =>
    translations[lang][key] ?? translations["en"][key] ?? key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      <div dir={lang === "ar" ? "rtl" : "ltr"}>{children}</div>
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
