import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "fr" | "ar";

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.journey": "Journey",
    "nav.education": "Education",
    "nav.experience": "Experience",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.ieee": "IEEE",
    "nav.awards": "Awards",
    "nav.testimonials": "Testimonials",
    "nav.uses": "Uses",
    "nav.contact": "Contact",
    "hero.greeting": "Hey there, I'm",
    "hero.currently": "Currently building:",
    "hero.at": "@ ADVISING LTD",
    "hero.download": "Download CV",
    "hero.view": "View Projects",
    "hero.available": "Available for Opportunities",
    "hero.badge": "Seeking Work-Study Program · Open to Opportunities",
    "about.title": "Who I Am",
    "about.subtitle": "Computer Science student with a passion for AI and full-stack development",
    "about.github": "GitHub Activity",
    "about.open": "Open to Opportunities",
    "about.open.sub": "International internships · Graduate programs · Global tech roles",
    "skills.title": "Technical Expertise",
    "skills.subtitle": "A comprehensive tech stack spanning AI, frontend, backend, and cloud",
    "experience.title": "Work Experience",
    "experience.subtitle": "Professional internships and engineering roles",
    "projects.title": "Projects",
    "projects.subtitle": "A selection of things I've built",
    "education.title": "Academic Journey",
    "education.subtitle": "The academic path that shaped my technical foundation",
    "contact.title": "Get In Touch",
    "contact.subtitle": "Let's collaborate and build something amazing together",
    "testimonials.title": "Kind Words",
    "testimonials.subtitle": "What colleagues and supervisors say about working with me",
    "journey.title": "My Story",
    "journey.subtitle": "The story behind the code — milestones that shaped who I am",
    "ieee.title": "IEEE Leadership",
    "ieee.subtitle": "Driving innovation and community across local, regional, and global IEEE initiatives",
    "awards.title": "Awards & Honors",
    "awards.subtitle": "Awards, certifications, and achievements",
    "uses.title": "My Setup",
    "uses.subtitle": "The tools, software, and hardware I use every day",
    "product.back": "Back to portfolio",
    "locali.status": "In development",
    "locali.eyebrow": "A new kind of workspace",
    "locali.tagline": "Your Personal AI Workspace",
    "locali.description": "A private, local-first space for understanding and working with your own files, projects, and knowledge through AI.",
    "locali.role": "Founder & Developer",
    "locali.byline": "A startup project by Mohamed Zouari",
    "locali.vision.label": "The vision",
    "locali.vision.title": "AI that stays close to you.",
    "locali.vision.first": "Locali is being explored as a calmer, more personal way to use AI: grounded in the context people already have, with privacy and control at the center.",
    "locali.vision.second": "The project is actively taking shape as a product idea for people who want useful intelligence around their digital lives without giving up ownership of them.",
    "locali.tag.private": "Private by design",
    "locali.tag.local": "Local-first",
    "locali.tag.active": "Actively developing",
    "locali.mock.private": "PRIVATE SPACE",
    "locali.mock.workspace": "Your workspace",
    "locali.mock.overview": "Overview",
    "locali.mock.projects": "Projects",
    "locali.mock.knowledge": "Knowledge",
    "locali.mock.files": "Files",
    "locali.mock.greeting": "Good morning, Mohamed",
    "locali.mock.heading": "Your space, understood.",
    "locali.mock.noticed": "Locali noticed",
    "locali.mock.noticedDescription": "You have three project notes from this week that connect to your current workspace.",
    "locali.mock.kept": "Kept within your space",
    "locali.mock.context": "LOCAL CONTEXT / READY",
    "revision.eyebrow": "A new chapter is taking shape",
    "revision.badge": "Coming soon",
    "revision.status": "Currently in development",
    "revision.tagline": "A new way to learn, revise, and grow.",
    "revision.description": "A Tunisian education project I am actively building for students, young people, teachers, and parents.",
    "revision.cta": "Explore what is next",
    "revision.mock.next": "Your next step",
    "revision.mock.roadmap": "Learning roadmap",
    "revision.mock.momentum": "Build your momentum.",
    "revision.mock.discover": "Discover",
    "revision.mock.learn": "Learn",
    "revision.mock.grow": "Grow",
    "revision.mock.footer": "A space for better study days",
    "revision.mock.community": "For the Tunisian learning community",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.journey": "Parcours",
    "nav.education": "Éducation",
    "nav.experience": "Expérience",
    "nav.projects": "Projets",
    "nav.skills": "Compétences",
    "nav.ieee": "IEEE",
    "nav.awards": "Prix",
    "nav.testimonials": "Avis",
    "nav.uses": "Outils",
    "nav.contact": "Contact",
    "hero.greeting": "Bonjour, je suis",
    "hero.currently": "En cours de développement :",
    "hero.at": "@ ADVISING LTD",
    "hero.download": "Télécharger CV",
    "hero.view": "Voir les projets",
    "hero.available": "Disponible pour des opportunités",
    "hero.badge": "Programme alternance · Ouvert aux opportunités",
    "about.title": "Qui suis-je",
    "about.subtitle": "Étudiant en informatique passionné par l'IA et le développement full-stack",
    "about.github": "Activité GitHub",
    "about.open": "Ouvert aux opportunités",
    "about.open.sub": "Stages internationaux · Programmes de master · Postes tech mondiaux",
    "skills.title": "Expertise Technique",
    "skills.subtitle": "Une stack complète couvrant IA, frontend, backend et cloud",
    "experience.title": "Expérience Pro",
    "experience.subtitle": "Stages professionnels et rôles d'ingénierie",
    "projects.title": "Projets",
    "projects.subtitle": "Une sélection de ce que j'ai construit",
    "education.title": "Parcours Académique",
    "education.subtitle": "Le parcours académique qui a forgé mes bases techniques",
    "contact.title": "Me Contacter",
    "contact.subtitle": "Collaborons et construisons quelque chose d'incroyable",
    "testimonials.title": "Témoignages",
    "testimonials.subtitle": "Ce que disent collègues et superviseurs",
    "journey.title": "Mon Parcours",
    "journey.subtitle": "L'histoire derrière le code — les étapes qui m'ont façonné",
    "ieee.title": "Leadership IEEE",
    "ieee.subtitle": "Promouvoir l'innovation et la communauté à travers les initiatives IEEE locales, régionales et mondiales",
    "awards.title": "Prix & Distinctions",
    "awards.subtitle": "Récompenses, certifications et réalisations",
    "uses.title": "Mon Environnement",
    "uses.subtitle": "Les outils, logiciels et matériels que j'utilise chaque jour",
    "product.back": "Retour au portfolio",
    "locali.status": "En développement",
    "locali.eyebrow": "Une nouvelle façon de travailler",
    "locali.tagline": "Votre espace de travail IA personnel",
    "locali.description": "Un espace privé et local pour comprendre et utiliser vos fichiers, projets et connaissances grâce à l'IA.",
    "locali.role": "Fondateur & Développeur",
    "locali.byline": "Un projet startup de Mohamed Zouari",
    "locali.vision.label": "La vision",
    "locali.vision.title": "Une IA qui reste proche de vous.",
    "locali.vision.first": "Locali explore une façon plus calme et personnelle d'utiliser l'IA, ancrée dans votre contexte, avec la confidentialité et le contrôle au centre.",
    "locali.vision.second": "Le projet prend forme comme un produit pour celles et ceux qui veulent une intelligence utile autour de leur vie numérique sans renoncer à la propriété de leurs données.",
    "locali.tag.private": "Privé par conception",
    "locali.tag.local": "Local avant tout",
    "locali.tag.active": "Développement actif",
    "locali.mock.private": "ESPACE PRIVÉ",
    "locali.mock.workspace": "Votre espace",
    "locali.mock.overview": "Vue d'ensemble",
    "locali.mock.projects": "Projets",
    "locali.mock.knowledge": "Connaissances",
    "locali.mock.files": "Fichiers",
    "locali.mock.greeting": "Bonjour, Mohamed",
    "locali.mock.heading": "Votre espace, compris.",
    "locali.mock.noticed": "Locali a remarqué",
    "locali.mock.noticedDescription": "Trois notes de cette semaine sont liées à votre espace de travail actuel.",
    "locali.mock.kept": "Conservé dans votre espace",
    "locali.mock.context": "CONTEXTE LOCAL / PRÊT",
    "revision.eyebrow": "Un nouveau chapitre prend forme",
    "revision.badge": "Bientôt disponible",
    "revision.status": "Actuellement en développement",
    "revision.tagline": "Une nouvelle façon d'apprendre, de réviser et de progresser.",
    "revision.description": "Un projet éducatif tunisien que je construis pour les étudiants, les jeunes, les enseignants et les parents.",
    "revision.cta": "Découvrir la suite",
    "revision.mock.next": "Votre prochaine étape",
    "revision.mock.roadmap": "Parcours d'apprentissage",
    "revision.mock.momentum": "Construisez votre élan.",
    "revision.mock.discover": "Découvrir",
    "revision.mock.learn": "Apprendre",
    "revision.mock.grow": "Progresser",
    "revision.mock.footer": "Un espace pour de meilleures journées d'étude",
    "revision.mock.community": "Pour la communauté éducative tunisienne",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.about": "عني",
    "nav.journey": "مسيرتي",
    "nav.education": "التعليم",
    "nav.experience": "الخبرة",
    "nav.projects": "المشاريع",
    "nav.skills": "المهارات",
    "nav.ieee": "IEEE",
    "nav.awards": "الجوائز",
    "nav.testimonials": "الآراء",
    "nav.uses": "الأدوات",
    "nav.contact": "التواصل",
    "hero.greeting": "مرحباً، أنا",
    "hero.currently": "أعمل حالياً على:",
    "hero.at": "@ ADVISING LTD",
    "hero.download": "تحميل السيرة الذاتية",
    "hero.view": "عرض المشاريع",
    "hero.available": "متاح للفرص",
    "hero.badge": "برنامج التعاون مع المؤسسات · مفتوح للفرص",
    "about.title": "من أنا",
    "about.subtitle": "طالب علوم الحاسوب شغوف بالذكاء الاصطناعي والتطوير الشامل",
    "about.github": "نشاط GitHub",
    "about.open": "متاح للفرص",
    "about.open.sub": "تدريبات دولية · برامج الدراسات العليا · وظائف تقنية عالمية",
    "skills.title": "الخبرة التقنية",
    "skills.subtitle": "مجموعة تقنيات شاملة تغطي الذكاء الاصطناعي والواجهات والخلفيات والسحابة",
    "experience.title": "الخبرة المهنية",
    "experience.subtitle": "تدريبات مهنية وأدوار هندسية",
    "projects.title": "المشاريع",
    "projects.subtitle": "مجموعة مختارة مما بنيته",
    "education.title": "المسيرة الأكاديمية",
    "education.subtitle": "المسار الأكاديمي الذي شكّل أسسي التقنية",
    "contact.title": "تواصل معي",
    "contact.subtitle": "لنتعاون ونبني شيئاً رائعاً معاً",
    "testimonials.title": "كلمات طيبة",
    "testimonials.subtitle": "ما يقوله الزملاء والمشرفون عن العمل معي",
    "journey.title": "قصتي",
    "journey.subtitle": "القصة خلف الكود — المحطات التي شكّلت مسيرتي",
    "ieee.title": "قيادة IEEE",
    "ieee.subtitle": "دفع الابتكار والمجتمع عبر مبادرات IEEE المحلية والإقليمية والعالمية",
    "awards.title": "الجوائز والتكريمات",
    "awards.subtitle": "الجوائز والشهادات والإنجازات",
    "uses.title": "بيئة عملي",
    "uses.subtitle": "الأدوات والبرامج والأجهزة التي أستخدمها يومياً",
    "product.back": "العودة إلى معرض الأعمال",
    "locali.status": "قيد التطوير",
    "locali.eyebrow": "مساحة عمل جديدة",
    "locali.tagline": "مساحة عملك الشخصية بالذكاء الاصطناعي",
    "locali.description": "مساحة خاصة ومحلية لفهم ملفاتك ومشاريعك ومعارفك والتعامل معها باستخدام الذكاء الاصطناعي.",
    "locali.role": "المؤسس والمطور",
    "locali.byline": "مشروع ناشئ من تطوير محمد الزواري",
    "locali.vision.label": "الرؤية",
    "locali.vision.title": "ذكاء اصطناعي يبقى قريباً منك.",
    "locali.vision.first": "يستكشف Locali طريقة أكثر هدوءاً وشخصية لاستخدام الذكاء الاصطناعي، تنطلق من سياقك مع وضع الخصوصية والتحكم في المركز.",
    "locali.vision.second": "يتشكل المشروع كفكرة منتج لمن يريد ذكاءً مفيداً حول حياته الرقمية دون التخلي عن ملكيته لها.",
    "locali.tag.private": "خصوصية من التصميم",
    "locali.tag.local": "محلي أولاً",
    "locali.tag.active": "تطوير مستمر",
    "locali.mock.private": "مساحة خاصة",
    "locali.mock.workspace": "مساحتك",
    "locali.mock.overview": "نظرة عامة",
    "locali.mock.projects": "المشاريع",
    "locali.mock.knowledge": "المعرفة",
    "locali.mock.files": "الملفات",
    "locali.mock.greeting": "صباح الخير، محمد",
    "locali.mock.heading": "مساحتك، مفهومة.",
    "locali.mock.noticed": "لاحظ Locali",
    "locali.mock.noticedDescription": "لديك ثلاث ملاحظات من هذا الأسبوع مرتبطة بمساحة عملك الحالية.",
    "locali.mock.kept": "تبقى داخل مساحتك",
    "locali.mock.context": "السياق المحلي / جاهز",
    "revision.eyebrow": "فصل جديد يتشكل",
    "revision.badge": "قريباً",
    "revision.status": "قيد التطوير حالياً",
    "revision.tagline": "طريقة جديدة للتعلم والمراجعة والنمو.",
    "revision.description": "مشروع تعليمي تونسي أعمل على تطويره للطلاب والشباب والمعلمين والأولياء.",
    "revision.cta": "اكتشف ما هو قادم",
    "revision.mock.next": "خطوتك التالية",
    "revision.mock.roadmap": "مسار التعلم",
    "revision.mock.momentum": "ابنِ تقدمك.",
    "revision.mock.discover": "اكتشف",
    "revision.mock.learn": "تعلّم",
    "revision.mock.grow": "تطوّر",
    "revision.mock.footer": "مساحة لأيام دراسية أفضل",
    "revision.mock.community": "للمجتمع التعليمي التونسي",
  },
};

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string =>
    translations[lang][key] ?? translations["en"][key] ?? key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      <div dir={lang === "ar" ? "rtl" : "ltr"}>{children}</div>
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
